# Generated by Django 4.2.5 on 2023-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
