# Generated by Django 4.2.5 on 2023-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_endereço_aluno_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
